### ISSUE TITLE
Please add multiple-node selection

### ISSUE THREAD

**Issue by powof2** [Unit978/UnityNodeEditorBase#9]
or make some examples so we can implement multiple-node-selection move, delete, clone operations, thank you.

and how about auto-layout function that is very useful (ok i can live without this though)?

p.s. thank you guys for the great tools.

**Comment by Siccity** [comment]
As a previous developer and the last person to commit to this project (7 months ago), I don't think it's in development anymore. However, on my profile you will find a battletested and frequently updated similar project called xNode. It has all the features you are requesting and more.

**Comment by powof2** [comment]
thank you for the reply, i'll check it out.
